#!/bin/bash

# vim:tw=80:tabstop=2:shiftwidth=2

# Copyright (c) 2012-present, Phil Dibowitz <phil@ipom.com>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in
#    binary form must reproduce the above copyright notice, this list of
#    conditions and the following disclaimer in the documentation and/or other
#    materials provided with the distribution.
#  * Neither the name of the author nor the names of its contributors may be
#    used to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#
# You can find the latest version of this at:
#   https://github.com/jaymzh/v6-gw-scripts
#
# Debian-style if-up.d script for firing off dhclient for ipv6
#

# Change EXT_IFACE by updating the config file

if [ "$ADDRFAM" != "inet6" ]; then
        exit 0
fi

echo -e "\n\n\nEntering 99-ipv6";

CONF='/etc/ipv6_prefix_dhclient.conf'
#EXT_IFACE="eth1"

[ -r $CONF ] && . $CONF

# We only care about the external interface.
if [ "$IFACE" != "$EXT_IFACE" ]; then
	exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

# If there's a stale dhclient, kill it

if [ -e /var/run/dhclient6.$IFACE.pid ]; then
	kill `cat /var/run/dhclient6.$IFACE.pid`
fi

echo "Waiting for interface $IFACE to finish Duplicate Address Detection (https://bugs.launchpad.net/ubuntu/+source/ifupdown/+bug/1543352)"
sleep 4

# Start our new one
#dhclient -6 -P -pf /var/run/dhclient6.$IFACE.pid -lf /var/lib/dhcp/dhclient6.$IFACE.leases $IFACE &

echo -e "\n\n\nStarting dhclient for IPv6"

dhclient -6 -P $IFACE -cf /etc/dhcp/dhclient6.conf -v -D LL -pf /var/run/dhclient6.$IFACE.pid -lf /var/lib/dhcp/dhclient6.$IFACE.leases

echo -e "\n\n\nKernel settings for $IFACE"

sysctl -w net/ipv6/conf/$IFACE/accept_ra=2
sysctl -w net/ipv6/conf/$IFACE/forwarding=1
sysctl -w net/ipv6/conf/$IFACE/autoconf=1
sysctl -w net/ipv6/neigh/$IFACE/base_reachable_time_ms=300000

# reload firewall rules
#/etc/network/ip6tables reload

exit 0
